# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character\n            <a href="https://www.isbn-international.org/content/what-isbn">\n                ISBN number\n            </a>', max_length=13, verbose_name='ISBN'),
        ),
    ]
